[package]
name = "sunholo/motoko_ext_compaction_structural"
version = "1.1.0"
edition = "1"

[dependencies]
"sunholo/motoko_ext_abi" = { path = "../motoko-ext-abi" }
"sunholo/motoko_core" = { path = "../../.packages/motoko_core" }

[effects]
max = ["IO", "Env", "AI", "Net", "FS", "Process", "SharedMem", "Clock", "Stream"]

[exports]
modules = [
  "sunholo/motoko_ext_compaction_structural/compaction_structural",
  "sunholo/motoko_ext_compaction_structural/register"
]
