#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import chdb

TOOL_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = TOOL_ROOT.parents[1]
OUT_DIR = TOOL_ROOT / ".out"
GRAPH_SCHEMA = 1
SOURCE_SCHEMA = 1
SCHEMAS = {
    "modules": "slug String, path String, module_decl String, decl_matches_path Int64, n_funcs Int64, is_generated Int64, is_root Int64, root_reason String",
    "funcs": "slug String, module String, name String, exported Int64, is_internal Int64, has_typed_sig Int64, type_sig String, declared_effects String, pure String, module_iface_status String",
    "types": "slug String, module String, name String, kind String, n_ctors Int64",
    "ctors": "slug String, module String, name String, type_slug String, source String",
    "imports": "from_module String, to_module String, alias String, symbols String",
    "invokes": "from_slug String, to_slug String, resolution String, approximate Int64",
    "std_calls": "from_slug String, std_module String, symbol String, resolution String",
    "uses": "from_slug String, type_slug String, resolved Int64",
    "effects": "func_slug String, effect String",
    "effect_edges": "func_slug String, effect String, source_func_slug String, distance Int64, derivation String",
    "source_files": "path String, module String, lang String, bytes Int64, sha256 String, n_lines Int64, profile String, include_tests UInt8",
    "source_lines": "path String, module String, lang String, line_no Int64, line String, is_comment UInt8, profile String, include_tests UInt8",
    "source_chunks": "chunk_slug String, func_slug String, path String, module String, lang String, kind String, name String, start_line Int64, end_line Int64, text String, profile String, include_tests UInt8",
    "extraction_status": "module String, iface_status String, iface_detail String, iface_error String, built_at String, ailang_version String, graph_schema Int64, source_schema Int64, iface_schema String, profile String, include_tests Int64",
    "concept_edges": "relation String, confidence Nullable(Float64), similarity Nullable(Float64), from_path String, from_heading String, to_path String, to_heading String, a_path String, b_path String, from_sha String, to_sha String, a_sha String, b_sha String, model String, strategy String",
    # Project 010 projections (generated by tools/code-graph/layout/build_layout.py
    # and tools/code-graph/overlay/build_activity.py; absent until those run).
    "layout": "node_id String, level Int64, x Float64, y Float64, radius Float64, snapshot String",
    "edges_agg": "level Int64, src_agg String, dst_agg String, kind String, weight Int64, exactness String",
    "activity": "seed Int64, event_idx Int64, record_key String, subject_id String, rule_kind String",
}
LAYOUT_TABLES = ("layout", "edges_agg")
_TOKEN_SUPPORT: bool | None = None


@dataclass(frozen=True)
class QueryFlags:
    effect_query: bool = False
    source_query: bool = False
    concept_query: bool = False
    layout_query: bool = False
    activity_query: bool = False
    search_mode: str | None = None


def csv_tables() -> list[str]:
    return sorted(p.stem for p in OUT_DIR.glob("*.csv"))


def view_preamble() -> str:
    parts = []
    for table in csv_tables():
        path = (OUT_DIR / f"{table}.csv").resolve()
        schema = SCHEMAS.get(table)
        if schema:
            parts.append(f"CREATE VIEW {table} AS SELECT * FROM file('{path}','CSVWithNames','{schema}');")
        else:
            parts.append(f"CREATE VIEW {table} AS SELECT * FROM file('{path}','CSVWithNames');")
    return "\n".join(parts) + "\n"


def run_sql(sql: str) -> dict:
    out = chdb.query(view_preamble() + sql, "JSON")
    return json.loads(str(out))


def sql_lit(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def token_supported() -> bool:
    global _TOKEN_SUPPORT
    if _TOKEN_SUPPORT is not None:
        return _TOKEN_SUPPORT
    if os.environ.get("CGQ_FORCE_TOKEN_PROBE_FAIL"):
        _TOKEN_SUPPORT = False
        return _TOKEN_SUPPORT
    try:
        chdb.query("SELECT hasToken('a b', 'b')", "JSON")
        _TOKEN_SUPPORT = True
    except Exception:
        _TOKEN_SUPPORT = False
    return _TOKEN_SUPPORT


def search_predicate(column: str, term: str, mode: str) -> tuple[str, str]:
    literal = sql_lit(term)
    if mode == "token":
        if token_supported():
            return f"hasToken({column}, {literal})", "token"
        return f"positionCaseInsensitive({column}, {literal}) > 0", "substring_fallback"
    return f"positionCaseInsensitive({column}, {literal}) > 0", "substring"


def live_ailang_version() -> str:
    try:
        return subprocess.run(["ailang", "--version"], capture_output=True, text=True, check=False,
                              cwd=REPO_ROOT).stdout.strip()
    except FileNotFoundError:
        return "ailang not found"


def _source_freshness(meta: dict) -> tuple[bool, str | None]:
    if not (OUT_DIR / "source_files.csv").exists():
        return True, "missing source_files"
    if int(meta.get("source_schema") or 0) != SOURCE_SCHEMA:
        return True, "source_schema mismatch"
    try:
        rows = run_sql("SELECT path, sha256 FROM source_files ORDER BY path").get("data", [])
    except Exception as exc:
        return True, f"source_files unreadable: {exc}"
    for row in rows:
        source = REPO_ROOT / row["path"]
        if not source.exists():
            return True, f"indexed source missing: {row['path']}"
        digest = hashlib.sha256(source.read_bytes()).hexdigest()
        if digest != row.get("sha256"):
            return True, f"indexed source hash mismatch: {row['path']}"
    return False, None


def _layout_snapshot_expected(status_rows: list[dict], profile: str) -> str | None:
    """Recompute the layout snapshot key from the current extraction, using the
    builder's own function so the two sides cannot drift on what "same
    snapshot" means. Returns None when the builder is unavailable."""
    sys.path.insert(0, str(TOOL_ROOT / "layout"))
    try:
        from build_layout import compute_snapshot  # type: ignore
    except Exception:
        return None
    return compute_snapshot(status_rows, profile)


def _layout_freshness(status_rows: list[dict], profile: str) -> tuple[bool, str | None, str | None]:
    """(stale, reason, stored_snapshot) for the layout projections."""
    if not (OUT_DIR / "layout.csv").exists():
        return True, "layout.csv missing (run tools/code-graph/layout/build_layout.py)", None
    try:
        rows = run_sql("SELECT DISTINCT snapshot AS s FROM layout").get("data", [])
    except Exception as exc:
        return True, f"layout unreadable: {exc}", None
    stored = sorted({row["s"] for row in rows})
    if len(stored) != 1:
        return True, f"layout carries {len(stored)} snapshot keys (expected exactly 1)", None
    expected = _layout_snapshot_expected(status_rows, profile)
    if expected is None:
        return True, "layout snapshot not verifiable (build_layout.py unavailable)", stored[0]
    if stored[0] != expected:
        return True, ("layout snapshot does not match the current extraction — "
                      "rerun tools/code-graph/layout/build_layout.py"), stored[0]
    return False, None, stored[0]


def _trace_file_count() -> int:
    traces = OUT_DIR / "traces"
    if not traces.is_dir():
        return 0
    return sum(1 for _ in traces.glob("*/*.jsonl"))


def status_meta(flags: QueryFlags | None = None) -> dict:
    flags = flags or QueryFlags()
    meta = {
        "built_at": None,
        "ailang_version": None,
        "graph_schema": None,
        "source_schema": None,
        "profile": None,
        "include_tests": False,
        "stale": True,
        "stale_reason": "missing extraction_status",
        "source_profile": None,
        "source_stale": True,
        "source_stale_reason": "missing source_files",
        "approximate": True,
        "coverage": {"ok": 0, "failed": 0, "partial": 0, "total": 0},
        "row_counts": {},
        "source_row_counts": {},
        "storage_mode": "csv_scan",
        "search_mode": flags.search_mode,
        "incomplete": False,
        "incomplete_modules": [],
        # Layout projections have their own freshness key (010 / Q7); activity is
        # keyed to trace files rather than to extractions, so it reports a count
        # instead of an extraction-staleness verdict.
        "layout_snapshot": None,
        "layout_stale": None,
        "layout_stale_reason": None,
        "activity_trace_files": None,
    }
    status_path = OUT_DIR / "extraction_status.csv"
    if not status_path.exists():
        return meta
    parsed = run_sql("SELECT * FROM extraction_status")
    rows = parsed.get("data", [])
    if not rows:
        return meta
    first = rows[0]
    meta["built_at"] = first.get("built_at")
    meta["ailang_version"] = first.get("ailang_version")
    meta["graph_schema"] = int(first.get("graph_schema") or 0)
    meta["source_schema"] = int(first.get("source_schema") or 0)
    meta["profile"] = first.get("profile") or "unknown"
    meta["source_profile"] = meta["profile"]
    meta["include_tests"] = bool(int(first.get("include_tests") or 0))
    counts = {"ok": 0, "failed": 0, "partial": 0, "total": len(rows)}
    incomplete = []
    for row in rows:
        st = row.get("iface_status", "")
        if st in counts:
            counts[st] += 1
        if st in {"failed", "partial"}:
            incomplete.append(row.get("module"))
    meta["coverage"] = counts
    for table in csv_tables():
        if table == "extraction_status":
            meta["row_counts"][table] = len(rows)
            continue
        try:
            meta["row_counts"][table] = int(run_sql(f"SELECT count() AS n FROM {table}")["data"][0]["n"])
        except Exception:
            pass
    for table in ("source_files", "source_lines", "source_chunks"):
        if table in meta["row_counts"]:
            meta["source_row_counts"][table] = meta["row_counts"][table]
    newest = 0.0
    for path in run_sql("SELECT path FROM modules").get("data", []):
        source = REPO_ROOT / path["path"]
        if source.exists():
            newest = max(newest, source.stat().st_mtime)
    stale_reason = None
    try:
        built_ts = __import__("datetime").datetime.fromisoformat(meta["built_at"]).timestamp()
        if newest > built_ts:
            stale_reason = "newer .ail mtime"
    except Exception:
        stale_reason = "invalid built_at"
    if meta["ailang_version"] != live_ailang_version():
        stale_reason = "ailang_version drift"
    if meta["graph_schema"] != GRAPH_SCHEMA:
        stale_reason = "graph_schema mismatch"
    meta["stale"] = stale_reason is not None
    meta["stale_reason"] = stale_reason
    source_stale, source_reason = _source_freshness(meta)
    meta["source_stale"] = source_stale
    meta["source_stale_reason"] = source_reason
    if flags.effect_query and (incomplete or meta["stale"]):
        meta["incomplete"] = True
        meta["incomplete_modules"] = incomplete
    if flags.layout_query:
        layout_stale, layout_reason, layout_snapshot = _layout_freshness(rows, meta["profile"])
        meta["layout_stale"] = layout_stale
        meta["layout_stale_reason"] = layout_reason
        meta["layout_snapshot"] = layout_snapshot
    if flags.activity_query:
        meta["activity_trace_files"] = _trace_file_count()
    return meta


def wrap(parsed: dict, limit: int, flags: QueryFlags | None = None) -> dict:
    flags = flags or QueryFlags()
    rows = parsed.get("data", [])
    total = len(rows)
    data = rows[:limit]
    meta = status_meta(flags)
    meta.update({"rows_returned": len(data), "rows_total": total, "truncated": total > len(data)})
    if flags.concept_query:
        meta["model_derived"] = True
        meta["model_caveat"] = ("concept_edges are LLM-extracted relations: confidence-scored "
                                "approximations, not facts. Audit low-confidence rows before relying on them.")
    return {"data": data, "meta": meta}


def flags_for_sql(sql: str) -> QueryFlags:
    """Raw SQL declares nothing, so the projections it touches are detected by
    name — that is what arms the layout staleness banner for ad-hoc queries."""
    lowered = sql.lower()
    return QueryFlags(
        layout_query=any(table in lowered for table in LAYOUT_TABLES),
        activity_query="activity" in lowered,
    )


def named_query(name: str, args: list[str]) -> tuple[str, QueryFlags]:
    if name == "module-deps":
        if args:
            mod = sql_lit(args[0])
            return f"SELECT * FROM imports WHERE from_module = {mod} OR to_module = {mod} ORDER BY from_module, to_module", QueryFlags()
        return "SELECT * FROM imports ORDER BY from_module, to_module", QueryFlags()
    if name == "importers":
        mod = sql_lit(args[0])
        return f"""
WITH RECURSIVE r(from_module, to_module, distance) AS (
  SELECT from_module, to_module, 1 FROM imports WHERE to_module = {mod}
  UNION ALL
  SELECT i.from_module, i.to_module, r.distance + 1 FROM imports i JOIN r ON i.to_module = r.from_module WHERE r.distance < 50
)
SELECT DISTINCT from_module AS importer FROM r ORDER BY importer
""", QueryFlags()
    if name == "callers":
        target = args[0]
        predicate = f"to_slug = {sql_lit(target)}" if "#" in target else f"to_slug LIKE {sql_lit('%#' + target)}"
        return f"""
WITH RECURSIVE r(from_slug, to_slug, distance) AS (
  SELECT from_slug, to_slug, 1 FROM invokes WHERE {predicate}
  UNION ALL
  SELECT i.from_slug, i.to_slug, r.distance + 1 FROM invokes i JOIN r ON i.to_slug = r.from_slug WHERE r.distance < 20
)
SELECT DISTINCT from_slug AS caller, min(distance) AS distance FROM r GROUP BY from_slug ORDER BY distance, caller
""", QueryFlags()
    if name == "reaches":
        eff = sql_lit(args[0])
        return f"SELECT DISTINCT func_slug, effect, min(distance) AS distance FROM effect_edges WHERE effect = {eff} GROUP BY func_slug, effect ORDER BY distance, func_slug", QueryFlags(effect_query=True)
    if name == "effects-of":
        func = args[0]
        predicate = f"func_slug = {sql_lit(func)}" if "#" in func else f"func_slug LIKE {sql_lit('%#' + func)}"
        return f"""
SELECT 'declared' AS kind, func_slug, effect, 0 AS distance FROM effects WHERE {predicate}
UNION ALL
SELECT 'reachable' AS kind, func_slug, effect, min(distance) AS distance FROM effect_edges WHERE {predicate} GROUP BY func_slug, effect
ORDER BY kind, effect
""", QueryFlags(effect_query=True)
    if name == "unimported":
        return """
WITH RECURSIVE reach(module, distance) AS (
  SELECT slug, 0 FROM modules WHERE is_root = 1
  UNION ALL
  SELECT i.to_module, r.distance + 1 FROM imports i JOIN reach r ON i.from_module = r.module WHERE r.distance < 50
)
SELECT slug AS module, 'unimported (not reachable via static imports from declared roots)' AS label
FROM modules WHERE slug NOT IN (SELECT DISTINCT module FROM reach) ORDER BY slug
""", QueryFlags()
    if name == "fan":
        mod = sql_lit(args[0])
        return f"""
SELECT m.slug AS module,
       (SELECT count() FROM imports WHERE to_module = m.slug) AS fan_in,
       (SELECT count() FROM imports WHERE from_module = m.slug) AS fan_out
FROM modules m WHERE m.slug = {mod}
""", QueryFlags()
    if name == "failures":
        return """
SELECT module, iface_status, iface_detail, iface_error
FROM extraction_status
WHERE iface_status IN ('partial', 'failed')
ORDER BY iface_status, module
""", QueryFlags()
    if name in {"search", "search-line"}:
        term = args[0]
        pred, mode = search_predicate("line", term, "substring")
        return f"""
SELECT path, line_no, lang, module, line
FROM source_lines
WHERE {pred}
ORDER BY path, line_no
""", QueryFlags(source_query=True, search_mode=mode)
    if name == "search-chunk":
        term = args[0]
        pred, mode = search_predicate("text", term, "substring")
        return f"""
SELECT chunk_slug, func_slug, path, module, lang, kind, name, start_line, end_line, left(text, 500) AS text_preview
FROM source_chunks
WHERE {pred}
ORDER BY path, start_line, chunk_slug
""", QueryFlags(source_query=True, search_mode=mode)
    if name == "search-effects":
        effect = sql_lit(args[0])
        term = args[1]
        pred, mode = search_predicate("c.text", term, "token")
        return f"""
SELECT c.func_slug AS func_slug, c.chunk_slug AS chunk_slug, f.name AS name, e.effect AS effect,
       c.path AS path, c.start_line AS start_line, c.end_line AS end_line, left(c.text, 500) AS text_preview
FROM source_chunks c
JOIN funcs f ON f.slug = c.func_slug
JOIN effect_edges e ON e.func_slug = c.func_slug
WHERE e.effect = {effect}
  AND {pred}
ORDER BY c.path, c.start_line
""", QueryFlags(effect_query=True, source_query=True, search_mode=mode)
    if name == "edges":
        like = sql_lit("%" + args[0] + "%")
        return f"""
SELECT relation, confidence, similarity,
       if(from_path != '', from_path, a_path) AS source,
       if(to_path != '', to_path, b_path) AS target
FROM concept_edges
WHERE from_path LIKE {like} OR to_path LIKE {like}
   OR a_path LIKE {like} OR b_path LIKE {like}
ORDER BY confidence DESC, relation
""", QueryFlags(concept_query=True)
    if name == "prereqs":
        like = sql_lit("%" + args[0] + "%")
        return f"""
SELECT from_path AS prerequisite, from_heading, to_path AS needed_for, to_heading, confidence
FROM concept_edges
WHERE relation = 'prerequisite' AND to_path LIKE {like}
ORDER BY confidence DESC, prerequisite
""", QueryFlags(concept_query=True)
    if name == "touched":
        seed = int(args[0])
        # THE shared subject-total query. `overlay/render_heat.py` renders from
        # this exact function rather than its own SQL, which is what makes the
        # picture and the query incapable of disagreeing (ADR acceptance);
        # `validate_overlay.py` then recomputes the totals independently and
        # asserts equality. Shared source, independent check.
        return f"""
SELECT subject_id,
       count() AS records,
       countIf(rule_kind = 'fixed') AS fixed,
       countIf(rule_kind = 'payload_routed') AS payload_routed,
       countIf(rule_kind = 'correlated') AS correlated,
       countIf(rule_kind = 'unattributed') AS unattributed
FROM activity
WHERE seed = {seed}
GROUP BY subject_id
ORDER BY records DESC, subject_id
""", QueryFlags(activity_query=True)
    if name == "divergence":
        # SCOPE LIMIT, STATED DELIBERATELY: this answers the TWO-SEED case only.
        # ADR D6 view 3 names the *same seed across two code versions* as the
        # primary divergence case, and the D1 `activity` schema cannot hold it —
        # it has no run-identity column, so two such runs collide on every key.
        # The information exists at the trace layer (the D9 header carries the
        # motoko commit) and is lost at this projection. That is plan Gap 10,
        # resolved at P5 by either a run column on `activity` (a D1 amendment,
        # argued then) or an anti-join over two trace stores — not papered over
        # here.
        a, b = int(args[0]), int(args[1])
        return f"""
SELECT 'first_divergence' AS kind,
       concat('idx ', toString(idx), ': ', if(ark = '', '(absent)', ark),
              ' vs ', if(brk = '', '(absent)', brk)) AS subject_id,
       toInt64(0) AS a_count, toInt64(0) AS b_count, toInt64(idx) AS delta
FROM (
  SELECT event_idx AS idx,
         anyIf(record_key, seed = {a}) AS ark,
         anyIf(record_key, seed = {b}) AS brk
  FROM activity WHERE seed IN ({a}, {b}) GROUP BY event_idx
)
WHERE ark != brk
ORDER BY idx
LIMIT 1
UNION ALL
SELECT 'subject_delta' AS kind, subject_id,
       toInt64(countIf(seed = {a})) AS a_count,
       toInt64(countIf(seed = {b})) AS b_count,
       toInt64(countIf(seed = {a}) - countIf(seed = {b})) AS delta
FROM activity WHERE seed IN ({a}, {b})
GROUP BY subject_id
HAVING a_count != b_count
ORDER BY kind, abs(delta) DESC, subject_id
""", QueryFlags(activity_query=True)
    if name in {"implements", "supersedes"}:
        like = sql_lit("%" + args[0] + "%")
        return f"""
SELECT from_path AS source, from_heading, to_path AS target, to_heading, confidence
FROM concept_edges
WHERE relation = {sql_lit(name)} AND (from_path LIKE {like} OR to_path LIKE {like})
ORDER BY confidence DESC, source
""", QueryFlags(concept_query=True)
    raise SystemExit(f"unknown named query: {name}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--format", choices=["json", "table"], default="json")
    ap.add_argument("--limit", type=int, default=200)
    ap.add_argument("--no-banner", action="store_true")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("status")
    sqlp = sub.add_parser("sql")
    sqlp.add_argument("sql")
    qp = sub.add_parser("q")
    qp.add_argument("name")
    qp.add_argument("args", nargs="*")
    ns = ap.parse_args()
    limit = max(0, min(ns.limit, 1000))
    flags = QueryFlags()
    if ns.cmd == "status":
        flags = QueryFlags(layout_query=True, activity_query=True)
        result = {"data": [], "meta": status_meta(flags)}
    elif ns.cmd == "sql":
        flags = flags_for_sql(ns.sql)
        result = wrap(run_sql(ns.sql), limit, flags)
    else:
        sql, flags = named_query(ns.name, ns.args)
        result = wrap(run_sql(sql), limit, flags)
    meta = result["meta"]
    if not ns.no_banner and flags.concept_query:
        print(f"MODEL-DERIVED: {meta.get('model_caveat')}", file=sys.stderr)
    if not ns.no_banner and not flags.concept_query and meta.get("stale"):
        print(f"STALE: {meta.get('stale_reason')}", file=sys.stderr)
    if not ns.no_banner and meta.get("source_stale") and meta.get("search_mode"):
        print(f"STALE: source index {meta.get('source_stale_reason')}", file=sys.stderr)
    if not ns.no_banner and meta.get("layout_stale"):
        print(f"STALE: {meta.get('layout_stale_reason')}", file=sys.stderr)
    if not ns.no_banner and meta.get("incomplete"):
        print("INCOMPLETE: effect answer is unknown where typed coverage is failed/partial or stale", file=sys.stderr)
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
